spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/jpa_db
    username: postgres
    password: tiger
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    database: postgresql
    show-sql: true
